# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-19 02:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pairs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeLapse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_same_team', models.BooleanField()),
                ('time_lapse_in_days', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to=b'profile'),
        ),
        migrations.AlterField(
            model_name='paircall',
            name='caption',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='paircall',
            name='picture',
            field=models.ImageField(blank=True, upload_to=b'paircall'),
        ),
        migrations.AddField(
            model_name='timelapse',
            name='primary_employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tl_employee_one', to='pairs.Employee'),
        ),
        migrations.AddField(
            model_name='timelapse',
            name='secondary_employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tl_employee_two', to='pairs.Employee'),
        ),
    ]
